[package]
name = "aeris"
version = "0.0.0"
edition = "2024"
description = "Unbounded package management"
license = "MIT"

[features]
debug = ["iced/hot"]

[dependencies]
async-trait = "0.1.89"
env_logger = "0.11.8"
iced = { version = "0.14.0", default-features = false, features = [
  "linux-theme-detection",
  "tiny-skia",
  "tokio",
  "wayland",
  "x11",
] }
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["sync"] }

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
codegen-units = 1
