[package]
name = "aeris"
version = "0.0.0"
edition = "2024"
description = "Unbounded package management"
license = "MIT"

[features]
debug = ["iced/hot"]

[dependencies]
env_logger = "0.11.8"
iced = { version = "0.14.0", default-features = false, features = [
  "linux-theme-detection",
  "thread-pool",
  "tiny-skia",
  "wayland",
  "x11"
] }
log = "0.4.29"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
codegen-units = 1
